spring:
   datasource:
      url: jdbc:mariadb://localhost:3306/mariadb
      driverClassName: org.mariadb.jdbc.Driver
      username: 
      password: 
   jpa:
      open-in-view: true
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create
        

#   security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: myid
#            client-secret: mysecretkey
            
