spring:
   datasource:
      url: jdbc:mariadb://localhost:3306/mariadb
      driverClassName: org.mariadb.jdbc.Driver
      username: jun
      password: tjgusskavys8*
   jpa:
      open-in-view: true
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create
        

   mail:
      host: smtp.gmail.com
      port: 8080
      username: jjwjun10@gmail.com
      password: tjgusskavys8*
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        
        
#   security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: myid
#            client-secret: mysecretkey
            
